In [15]:
#importing data set
import pandas as pd
filename="C:/Users/Sidharth Jahagirdar/Desktop/First Sem/Spotify_2018/spotifyclassification/data.csv"
df=pd.read_csv(filename,encoding='ISO_8859_1')
df.head(10)

Unnamed: 0  acousticness  danceability  duration_ms  energy  \
0           0       0.01020         0.833       204600   0.434   
1           1       0.19900         0.743       326933   0.359   
2           2       0.03440         0.838       185707   0.412   
3           3       0.60400         0.494       199413   0.338   
4           4       0.18000         0.678       392893   0.561   
5           5       0.00479         0.804       251333   0.560   
6           6       0.01450         0.739       241400   0.472   
7           7       0.02020         0.266       349667   0.348   
8           8       0.04810         0.603       202853   0.944   
9           9       0.00208         0.836       226840   0.603   

   instrumentalness  key  liveness  loudness  mode  speechiness    tempo  \
0          0.021900    2    0.1650    -8.795     1       0.4310  150.062   
1          0.006110    1    0.1370   -10.401     1       0.0794  160.083   
2          0.000234    2    0.1590    -7.148     1       0.2890   75.044   
3          0.510000    5    0.0922   -15.236     1       0.0261   86.468   
4          0.512000    5    0.4390   -11.648     0       0.0694  174.004   
5          0.000000    8    0.1640    -6.682     1       0.1850   85.023   
6          0.000007    1    0.2070   -11.204     1       0.1560   80.030   
7          0.664000   10    0.1600   -11.609     0       0.0371  144.154   
8          0.000000   11    0.3420    -3.626     0       0.3470  130.035   
9          0.000000    7    0.5710    -7.792     1       0.2370   99.994   

   time_signature  valence  target          song_title            artist  
0             4.0    0.286       1            Mask Off            Future  
1             4.0    0.588       1             Redbone  Childish Gambino  
2             4.0    0.173       1        Xanny Family            Future  
3             4.0    0.230       1      Master Of None       Beach House  
4             4.0    0.904       1      Parallel Lines       Junior Boys  
5             4.0    0.264       1          Sneakin’             Drake  
6             4.0    0.308       1         Childs Play             Drake  
7             4.0    0.393       1  Gyöngyhajú lány             Omega  
8             4.0    0.398       1   I've Seen Footage       Death Grips  
9             4.0    0.386       1      Digital Animal       Honey Claws

In [16]:
#import libraries needed to perform regression analysis
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import numpy as np

In [17]:
#Data Cleaning
new_order=[2,1,4,5,7,8,11,10,13]
df=df[df.columns[new_order]]

In [18]:
#Defining dependent and independent variables
x=df.iloc[:,1:].values
y=df.iloc[:,0:1].values

In [19]:
df.head(10)

danceability  acousticness  energy  instrumentalness  liveness  loudness  \
0         0.833       0.01020   0.434          0.021900    0.1650    -8.795   
1         0.743       0.19900   0.359          0.006110    0.1370   -10.401   
2         0.838       0.03440   0.412          0.000234    0.1590    -7.148   
3         0.494       0.60400   0.338          0.510000    0.0922   -15.236   
4         0.678       0.18000   0.561          0.512000    0.4390   -11.648   
5         0.804       0.00479   0.560          0.000000    0.1640    -6.682   
6         0.739       0.01450   0.472          0.000007    0.2070   -11.204   
7         0.266       0.02020   0.348          0.664000    0.1600   -11.609   
8         0.603       0.04810   0.944          0.000000    0.3420    -3.626   
9         0.836       0.00208   0.603          0.000000    0.5710    -7.792   

     tempo  speechiness  valence  
0  150.062       0.4310    0.286  
1  160.083       0.0794    0.588  
2   75.044       0.2890    0.173  
3   86.468       0.0261    0.230  
4  174.004       0.0694    0.904  
5   85.023       0.1850    0.264  
6   80.030       0.1560    0.308  
7  144.154       0.0371    0.393  
8  130.035       0.3470    0.398  
9   99.994       0.2370    0.386

In [20]:
x.shape

(2017, 8)

In [21]:
y.shape

(2017, 1)

In [22]:
#Splitting data into train and test data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.05)

In [23]:
#Creating Regression Model
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
#Creating trial data using Test data example of test data index 6 is shown here
trial_data=x_test[29]
trial_data=trial_data.reshape(-1,8)
trial_data=trial_data.astype(float)

In [25]:
#Predicting values on test data
regressor.predict(trial_data)

array([[0.70421975]])

In [26]:
#Getting input for test data 
x_test[29]

array([ 2.1900e-01,  5.1500e-01,  0.0000e+00,  1.2400e-01, -1.3029e+01,
        8.5023e+01,  6.0500e-02,  7.1200e-01])

In [27]:
#Getting actual result of test data
y_test[29]

array([0.698])

In [28]:
#The difference between actual results and predicted results is 
#because of the unknown factors which can't be predicted or taken into consideration